/**
 * Seed cases bundled with Detective Data so the app has content on first load.
 * These are plain CSV strings — parsed at runtime through the exact same
 * lib/csv-parser.ts engine an admin's uploaded CSV goes through.
 * Auto-generated from /data/*.csv — do not hand-edit, edit the CSVs instead.
 */

export const case001Csv: string = "Type,Key,Value,ID,Time,Source,Actor,Action,Object,Target,Location,Description,Importance\r\nMETA,CASE_ID,CASE001,,,,,,,,,,\r\nMETA,TITLE,Laptop Hilang di Kantor,,,,,,,,,,\r\nMETA,DIFFICULTY,Easy,,,,,,,,,,\r\nMETA,CATEGORY,Theft,,,,,,,,,,\r\nMETA,TIME_LIMIT,15,,,,,,,,,,\r\nMETA,MAX_SCORE,100,,,,,,,,,,\r\nMETA,STORY,\"Pada hari Senin, Pak Budi melaporkan laptop kantornya hilang setelah kembali dari rapat. Seluruh bukti investigasi tersedia dalam bentuk CCTV, GPS, chat, transaksi, dan hasil forensik. Analisis seluruh data untuk menemukan pelaku.\",,,,,,,,,,\r\nMETA,QUESTION,Siapa pelaku pencurian laptop? Jelaskan alasan investigasi Anda berdasarkan bukti yang ditemukan.,,,,,,,,,,\r\nMETA,CULPRIT,Andi,,,,,,,,,,\r\nMETA,SOLUTION,\"Berdasarkan rekaman CCTV, data GPS, dan sidik jari yang ditemukan di meja korban, Andi adalah satu-satunya orang yang memiliki kesempatan mengambil laptop sebelum meninggalkan ruangan membawa tas hitam.\",,,,,,,,,,\r\nMETA,REFERENCE_EVENTS,5|6|8|10,,,,,,,,,,\r\nMETA,HINT,Perhatikan urutan waktu kejadian dan siapa yang berada sendirian di ruangan sebelum laptop dinyatakan hilang.,,,,,,,,,,\r\nEVENT,,,1,08:00,Attendance,Andi,Check In,,,Lobby,Andi masuk kantor,1\r\nEVENT,,,2,08:03,Attendance,Eva,Check In,,,Lobby,Eva masuk kantor,1\r\nEVENT,,,3,08:05,Attendance,Citra,Check In,,,Lobby,Citra masuk kantor,1\r\nEVENT,,,4,13:45,CCTV,Pak Budi,Exit,,,Pak Budi Office,Pak Budi keluar menuju ruang rapat,3\r\nEVENT,,,5,13:53,CCTV,Andi,Enter,,,Pak Budi Office,Andi masuk ke ruang Pak Budi,5\r\nEVENT,,,6,13:55,GPS,Andi,Stay,,,Pak Budi Office,Andi berada sendirian di dalam ruangan,5\r\nEVENT,,,7,14:00,Incident,System,Report,Laptop,,Pak Budi Office,Laptop dinyatakan hilang,5\r\nEVENT,,,8,14:02,CCTV,Andi,Exit,,,Pak Budi Office,Andi keluar membawa tas hitam,5\r\nEVENT,,,9,14:03,GPS,Andi,Move,,,Lift Area,Andi menuju lift,4\r\nEVENT,,,10,15:30,Forensic,System,Find,Fingerprint,Andi,Pak Budi Office,Sidik jari Andi ditemukan pada meja laptop,5\r\n";

export const case002Csv: string = "Type,Key,Value,ID,Time,Source,Actor,Action,Object,Target,Location,Description,Importance\nMETA,CASE_ID,CASE002,,,,,,,,,,\nMETA,TITLE,Transfer Misterius Dana Perusahaan,,,,,,,,,,\nMETA,DIFFICULTY,Medium,,,,,,,,,,\nMETA,CATEGORY,Fraud,,,,,,,,,,\nMETA,TIME_LIMIT,20,,,,,,,,,,\nMETA,MAX_SCORE,150,,,,,,,,,,\nMETA,STORY,\"Bagian keuangan menemukan transfer dana sebesar Rp 85 juta ke rekening tidak dikenal pada akhir bulan. Empat staf memiliki akses ke sistem keuangan pada hari kejadian. Telusuri log transaksi, email, dan chat internal untuk mengungkap siapa yang bertanggung jawab.\",,,,,,,,,,\nMETA,QUESTION,Siapa yang melakukan transfer dana tidak sah tersebut? Jelaskan alasan investigasi Anda berdasarkan bukti yang ditemukan.,,,,,,,,,,\nMETA,CULPRIT,Deni,,,,,,,,,,\nMETA,SOLUTION,\"Log transaksi menunjukkan Deni login ke sistem keuangan pada pukul 23.10 menggunakan kredensial miliknya sendiri, lalu mengirim email konfirmasi ke rekening baru yang ia buat dua hari sebelumnya. Chat internal juga menunjukkan Deni sempat menanyakan cara membatalkan jejak transaksi kepada rekannya.\",,,,,,,,,,\nMETA,REFERENCE_EVENTS,4|6|7|9,,,,,,,,,,\nMETA,HINT,Perhatikan siapa yang mengakses sistem di luar jam kerja normal dan siapa yang membuat rekening baru menjelang kejadian.,,,,,,,,,,\nEVENT,,,1,08:30,Attendance,Deni,Check In,,,Kantor Pusat,Deni masuk kantor seperti biasa,1\nEVENT,,,2,08:40,Attendance,Rina,Check In,,,Kantor Pusat,Rina masuk kantor,1\nEVENT,,,3,09:15,Email,Deni,Send,Formulir Rekening Baru,Bank,Kantor Pusat,Deni mengirim formulir pembukaan rekening baru ke bank,3\nEVENT,,,4,22:50,Transaction,Deni,Login,Sistem Keuangan,,Remote,Deni login ke sistem keuangan dari luar kantor pada malam hari,5\nEVENT,,,5,22:55,Chat,Deni,Message,,Rina,Grup Chat Internal,Deni bertanya cara menghapus jejak transaksi kepada Rina,4\nEVENT,,,6,23:05,Chat,Rina,Message,,Deni,Grup Chat Internal,Rina menjawab bahwa log transaksi tidak bisa dihapus,3\nEVENT,,,7,23:10,Transaction,Deni,Transfer,Dana Rp85.000.000,Rekening Tidak Dikenal,Remote,Transfer dana sebesar Rp85 juta dilakukan dari akun Deni,5\nEVENT,,,8,23:12,Transaction,System,Log,Transfer,,Server Keuangan,Sistem mencatat transaksi keluar sebesar Rp85 juta,5\nEVENT,,,9,23:20,Email,Deni,Send,Konfirmasi Transfer,Bank,Remote,Deni mengirim email konfirmasi transfer ke bank tujuan,5\nEVENT,,,10,07:00,Attendance,Deni,Check In,,,Kantor Pusat,Deni masuk kantor seperti biasa keesokan harinya,1\n";

export const case003Csv: string = "Type,Key,Value,ID,Time,Source,Actor,Action,Object,Target,Location,Description,Importance\nMETA,CASE_ID,CASE003,,,,,,,,,,\nMETA,TITLE,Barang Gudang yang Menghilang,,,,,,,,,,\nMETA,DIFFICULTY,Hard,,,,,,,,,,\nMETA,CATEGORY,Theft,,,,,,,,,,\nMETA,TIME_LIMIT,25,,,,,,,,,,\nMETA,MAX_SCORE,200,,,,,,,,,,\nMETA,STORY,\"Sebuah gudang penyimpanan kehilangan beberapa unit barang elektronik senilai puluhan juta rupiah. Gudang dilengkapi sensor pintu IoT, CCTV, dan sistem absensi. Empat pekerja memiliki akses ke gudang pada malam kejadian. Analisis seluruh jejak digital untuk menemukan siapa yang benar-benar masuk dan mengambil barang.\",,,,,,,,,,\nMETA,QUESTION,Siapa yang mengambil barang dari gudang? Jelaskan alasan investigasi Anda berdasarkan bukti yang ditemukan.,,,,,,,,,,\nMETA,CULPRIT,Citra,,,,,,,,,,\nMETA,SOLUTION,\"Sensor pintu IoT mencatat pintu gudang terbuka pukul 01.12 menggunakan kartu akses milik Citra, tepat setelah CCTV menunjukkan Citra kembali ke area gudang. GPS kendaraan Citra juga menunjukkan pergerakan menuju gudang pada jam yang sama, berbeda dari jadwal shift-nya yang seharusnya sudah selesai pukul 22.00.\",,,,,,,,,,\nMETA,REFERENCE_EVENTS,5|7|8|9,,,,,,,,,,\nMETA,HINT,Bandingkan jadwal shift resmi setiap pekerja dengan waktu sebenarnya sensor pintu dan CCTV mencatat pergerakan mereka.,,,,,,,,,,\nEVENT,,,1,18:00,Attendance,Andi,Check In,,,Gudang Utama,Andi mulai shift malam,1\nEVENT,,,2,18:00,Attendance,Citra,Check In,,,Gudang Utama,Citra mulai shift malam,1\nEVENT,,,3,22:00,Attendance,Citra,Check Out,,,Gudang Utama,Citra tercatat check out sesuai jadwal shift,2\nEVENT,,,4,22:05,CCTV,Citra,Exit,,,Pintu Depan Gudang,CCTV merekam Citra meninggalkan gudang melalui pintu depan,2\nEVENT,,,5,01:05,GPS,Citra,Move,,,Area Parkir Gudang,GPS kendaraan Citra menunjukkan kembali ke area gudang tengah malam,4\nEVENT,,,6,01:10,CCTV,Citra,Enter,,,Pintu Belakang Gudang,CCTV merekam Citra masuk kembali lewat pintu belakang,5\nEVENT,,,7,01:12,IoT Sensor,Citra,Unlock,Pintu Gudang,,Gudang Utama,Sensor pintu mencatat akses menggunakan kartu milik Citra,5\nEVENT,,,8,01:20,IoT Sensor,Citra,Move,Rak B3,,Gudang Utama,Sensor gerak mendeteksi aktivitas di rak elektronik B3,5\nEVENT,,,9,01:35,CCTV,Citra,Exit,Kotak Kardus,,Pintu Belakang Gudang,CCTV merekam Citra keluar membawa dua kotak kardus besar,5\nEVENT,,,10,06:00,Attendance,Andi,Check Out,,,Gudang Utama,Andi menyelesaikan shift malam tanpa insiden,1\n";

export const seedCaseCsvs: string[] = [case001Csv, case002Csv, case003Csv];
